version: '3.8'

services:
  aras_auth:
    image: ghcr.io/aras-group-co/aras-auth:${ARAS_AUTH_VERSION}
    container_name: aras_auth_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Server Configuration
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 7600
      
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: ${POSTGRES_DB:-allgram}
      DB_SSL_MODE: disable
      
      # JWT Configuration
      JWT_SECRET_KEY: ${JWT_SECRET:-change-me-please-32b-min}
      JWT_ACCESS_EXPIRY: 15m
      JWT_REFRESH_EXPIRY: 168h
      
      # Admin Configuration
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@allgram.local}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin123}
    ports:
      - "7600:7600"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:7600/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - aras_auth_network

  postgres:
    image: postgres:15-alpine
    container_name: aras_auth_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-allgram}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aras_auth_network

volumes:
  postgres_data:
    driver: local

networks:
  aras_auth_network:
    driver: bridge

