-- Rollback script
ALTER TABLE users DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS deleted_by;
ALTER TABLE groups DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS deleted_by;
ALTER TABLE roles DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS deleted_by;
ALTER TABLE permissions DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS deleted_at, DROP COLUMN IF EXISTS deleted_by;
