-- Rollback script
ALTER TABLE users DROP COLUMN IF EXISTS is_deleted;
ALTER TABLE groups DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS is_deleted;
ALTER TABLE roles DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS is_deleted;
ALTER TABLE permissions DROP COLUMN IF EXISTS is_active, DROP COLUMN IF EXISTS is_deleted;
